---
- name: Set timezone
  timezone:
    name: "{{ time_zone }}"

- name: Install chrony
  yum:
    name: chrony
    state: present

- name: Start service
  systemd:
    name: chronyd.service
    state: started
    enabled: yes
